version: '3.4'

services:
  traefik:
    image: traefik
    command: --api --docker
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  php:
    image: ${CONTAINER_REGISTRY_BASE}/php
    build:
      context: ./api
      target: api_platform_php
      cache_from:
        - ${CONTAINER_REGISTRY_BASE}/php
        - ${CONTAINER_REGISTRY_BASE}/nginx
        - ${CONTAINER_REGISTRY_BASE}/varnish
    environment:
      - APP_URL=${HTTP_OR_SSL}${DOMAIN_NAME}
      - TRUSTED_HOSTS=^api.${DOMAIN_NAME}$$
      - CORS_ALLOW_ORIGIN=^https?://((api|cache|preprod)\.)?${DOMAIN_NAME}(:[0-9]+)?$$
      - DATABASE_URL=postgres://${DB_USERNAME}:${DB_PASSWORD}@db/${DB_HOST}
    links:
      - mailer
    depends_on:
      - db
      - mailer
    volumes:
      - ./api:/srv/api:rw,cached
    networks:
      - escort

  api:
    image: ${CONTAINER_REGISTRY_BASE}/nginx
    build:
      context: ./api
      target: api_platform_nginx
      cache_from:
        - ${CONTAINER_REGISTRY_BASE}/php
        - ${CONTAINER_REGISTRY_BASE}/nginx
        - ${CONTAINER_REGISTRY_BASE}/varnish
    depends_on:
      - php
    volumes:
      - ./api/public:/srv/api/public:ro
    labels:
      - traefik.frontend.rule=Host:api.${DOMAIN_NAME}
    networks:
      - escort

  cache-proxy:
    image: ${CONTAINER_REGISTRY_BASE}/varnish
    build:
      context: ./api
      target: api_platform_varnish
      cache_from:
        - ${CONTAINER_REGISTRY_BASE}/php
        - ${CONTAINER_REGISTRY_BASE}/nginx
        - ${CONTAINER_REGISTRY_BASE}/varnish
    depends_on:
      - api
    volumes:
      - ./api/docker/varnish/conf:/usr/local/etc/varnish:ro
    tmpfs:
      - /usr/local/var/varnish:exec
    labels:
      - traefik.frontend.rule=Host:cache.${DOMAIN_NAME}
    networks:
      - escort

  db:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_DB=${DB_HOST}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    networks:
      - escort

  client:
    image: ${CONTAINER_REGISTRY_BASE}/client
    build:
      context: ./client
      cache_from:
        - ${CONTAINER_REGISTRY_BASE}/client
    env_file:
      - ./client/.env
    volumes:
      - ./client:/usr/src/client:rw,cached
      - /usr/src/client/node_modules
    environment:
      - REACT_APP_API_ENTRYPOINT=${HTTP_OR_SSL}cache.${DOMAIN_NAME}
    expose:
      - 3000
    labels:
      - traefik.frontend.rule=Host:preprod.${DOMAIN_NAME}
      - traefik.port=3000
    networks:
      - escort
  
  mailer:
    image: juanluisbaptiste/postfix:latest
    restart: always
    environment:
      - SMTP_PORT=587
      - SMTP_SERVER=smtp.eu.mailgun.org
      - SMTP_USERNAME=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SERVER_HOSTNAME=${DOMAIN_NAME}
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
    networks:
      - escort
    

  cdn:
    image: nginx:latest
    build:
      context: ./cdn
    volumes:
      - ./cdn/build:/usr/share/nginx/html:ro
    labels:
      - traefik.frontend.rule=Host:${DOMAIN_NAME}
    networks:
      - escort

volumes:
  db-data: {}

networks:
  escort:
    external: true
