#index:
#    path: /
#    controller: App\Controller\DefaultController::index

login:
    path: /login

participate:
    path: /participate
    methods: [POST]
    controller: App\Controller\Participate
