export const RETRIEVE_OUTINGS_LIST_FAILED = 'RETRIEVE_OUTINGS_LIST_FAILED';
export const RETRIEVE_OUTINGS_LIST_REQUEST = 'RETRIEVE_OUTINGS_LIST_REQUEST';
export const RETRIEVE_OUTINGS_LIST_SUCCESS = 'RETRIEVE_OUTINGS_LIST_SUCCESS';

export const getOutingsList = data => ({
  type: RETRIEVE_OUTINGS_LIST_REQUEST,
  payload: data
});
